In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from rich import print # This makes print way prettier

In [2]:
input_data = pd.read_csv("apple_quality.csv")
input_data

A_id      Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness  \
0        0.0 -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840   
1        1.0 -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530   
2        2.0 -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033   
3        3.0 -0.657196 -2.271627   1.324874    -0.097875   3.637970 -3.413761   
4        4.0  1.364217 -1.296612  -0.384658    -0.553006   3.030874 -1.303849   
...      ...       ...       ...        ...          ...        ...       ...   
3996  3996.0 -0.293118  1.949253  -0.204020    -0.640196   0.024523 -1.087900   
3997  3997.0 -2.634515 -2.138247  -2.440461     0.657223   2.199709  4.763859   
3998  3998.0 -4.008004 -1.779337   2.366397    -0.200329   2.161435  0.214488   
3999  3999.0  0.278540 -1.715505   0.121217    -1.154075   1.266677 -0.776571   
4000     NaN       NaN       NaN        NaN          NaN        NaN       NaN   

                                Acidity Quality  
0                          -0.491590483    good  
1                          -0.722809367    good  
2                           2.621636473     bad  
3                           0.790723217    good  
4                           0.501984036    good  
...                                 ...     ...  
3996                        1.854235285    good  
3997                       -1.334611391     bad  
3998                       -2.229719806    good  
3999                        1.599796456    good  
4000  Created_by_Nidula_Elgiriyewithana     NaN  

[4001 rows x 9 columns]

In [3]:
input_data.isnull().sum()


A_id           1
Size           1
Weight         1
Sweetness      1
Crunchiness    1
Juiciness      1
Ripeness       1
Acidity        0
Quality        1
dtype: int64

In [4]:
input_data.dropna(inplace=True)

In [5]:
input_data.shape


(4000, 9)

In [6]:
input_data.info()


<class 'pandas.core.frame.DataFrame'>
Index: 4000 entries, 0 to 3999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   A_id         4000 non-null   float64
 1   Size         4000 non-null   float64
 2   Weight       4000 non-null   float64
 3   Sweetness    4000 non-null   float64
 4   Crunchiness  4000 non-null   float64
 5   Juiciness    4000 non-null   float64
 6   Ripeness     4000 non-null   float64
 7   Acidity      4000 non-null   object 
 8   Quality      4000 non-null   object 
dtypes: float64(7), object(2)
memory usage: 312.5+ KB


In [7]:
input_data['Acidity']=input_data['Acidity'].astype("float64")

In [8]:
input_data.info()


<class 'pandas.core.frame.DataFrame'>
Index: 4000 entries, 0 to 3999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   A_id         4000 non-null   float64
 1   Size         4000 non-null   float64
 2   Weight       4000 non-null   float64
 3   Sweetness    4000 non-null   float64
 4   Crunchiness  4000 non-null   float64
 5   Juiciness    4000 non-null   float64
 6   Ripeness     4000 non-null   float64
 7   Acidity      4000 non-null   float64
 8   Quality      4000 non-null   object 
dtypes: float64(8), object(1)
memory usage: 312.5+ KB


In [9]:
labels_array = input_data['Quality'].to_numpy()
labels_array

array(['good', 'good', 'bad', ..., 'bad', 'good', 'good'], dtype=object)

In [10]:
features_no = 7
data_array = np.zeros((len(input_data), features_no))
for i in range(len(input_data)):
    data_array[i] = input_data.iloc[i][1:8].to_numpy()

data_array

array([[-3.97004852, -2.51233638,  5.34632961, ...,  1.84490036,
         0.3298398 , -0.49159048],
       [-1.19521719, -2.83925653,  3.66405876, ...,  0.8532858 ,
         0.86753008, -0.72280937],
       [-0.29202386, -1.35128199, -1.73842916, ...,  2.83863551,
        -0.03803333,  2.62163647],
       ...,
       [-2.6345153 , -2.13824672, -2.44046129, ...,  2.19970859,
         4.76385918, -1.33461139],
       [-4.00800374, -1.77933711,  2.36639697, ...,  2.16143512,
         0.21448838, -2.22971981],
       [ 0.27853965, -1.71550503,  0.12121725, ...,  1.2666774 ,
        -0.77657147,  1.59979646]])

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(labels_array)
labels_array = le.fit_transform(labels_array)

labels_array

array([1, 1, 0, ..., 0, 1, 1])

In [12]:
from sklearn.preprocessing import normalize

data_array = normalize(data_array)
data_array


array([[-0.53321852, -0.33743272,  0.71806728, ...,  0.24778917,
         0.04430089, -0.06602568],
       [-0.22816433, -0.54200781,  0.69946074, ...,  0.16289038,
         0.16560958, -0.13798271],
       [-0.06532623, -0.30228405, -0.38888952, ...,  0.63500752,
        -0.00850812,  0.58646447],
       ...,
       [-0.38340833, -0.31118498, -0.35516711, ...,  0.3201297 ,
         0.69329766, -0.1942297 ],
       [-0.68177964, -0.30267332,  0.40253487, ...,  0.36766993,
         0.03648545, -0.37928546],
       [ 0.09216294, -0.56762473,  0.04010825, ...,  0.41911706,
        -0.25695126,  0.52933919]])

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data_array, labels_array,
                                                    test_size=0.2, random_state=42)

In [14]:
from sklearn.metrics import classification_report # Our metric module


In [15]:
from sklearn.ensemble import RandomForestClassifier

quality_types = ["good", "bad"]

rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

y_pred_rfc = rfc.predict(X_test)
print(classification_report(y_test, y_pred_rfc, target_names=quality_types))

precision    recall  f1-score   support

        good       0.90      0.89      0.90       401
         bad       0.89      0.90      0.90       399

    accuracy                           0.90       800
   macro avg       0.90      0.90      0.90       800
weighted avg       0.90      0.90      0.90       800

In [16]:
from sklearn.ensemble import ExtraTreesClassifier

erfc = ExtraTreesClassifier()
erfc.fit(X_train, y_train)

y_pred_erfc = erfc.predict(X_test)
print(classification_report(y_test, y_pred_erfc, target_names=quality_types))

precision    recall  f1-score   support

        good       0.90      0.90      0.90       401
         bad       0.90      0.90      0.90       399

    accuracy                           0.90       800
   macro avg       0.90      0.90      0.90       800
weighted avg       0.90      0.90      0.90       800

In [17]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)
print(classification_report(y_test, y_pred_knn, target_names=quality_types))


precision    recall  f1-score   support

        good       0.90      0.90      0.90       401
         bad       0.90      0.90      0.90       399

    accuracy                           0.90       800
   macro avg       0.90      0.90      0.90       800
weighted avg       0.90      0.90      0.90       800

In [18]:
from sklearn.svm import SVC

svc_lin = SVC(kernel='linear')
svc_lin.fit(X_train, y_train)

y_pred_svc_lin = svc_lin.predict(X_test)
print(classification_report(y_test, y_pred_svc_lin, target_names=quality_types))

precision    recall  f1-score   support

        good       0.76      0.75      0.75       401
         bad       0.75      0.76      0.75       399

    accuracy                           0.75       800
   macro avg       0.75      0.75      0.75       800
weighted avg       0.75      0.75      0.75       800

In [19]:
svc_poly = SVC(kernel='poly')
svc_poly.fit(X_train, y_train)

y_pred_svc_poly = svc_poly.predict(X_test)
print(classification_report(y_test, y_pred_svc_poly, target_names=quality_types))

precision    recall  f1-score   support

        good       0.89      0.88      0.89       401
         bad       0.88      0.89      0.89       399

    accuracy                           0.89       800
   macro avg       0.89      0.89      0.89       800
weighted avg       0.89      0.89      0.89       800

In [20]:
svc_rbf = SVC(kernel='rbf')
svc_rbf.fit(X_train, y_train)

y_pred_svc_rbf = svc_rbf.predict(X_test)
print(classification_report(y_test, y_pred_svc_rbf, target_names=quality_types))

precision    recall  f1-score   support

        good       0.91      0.90      0.91       401
         bad       0.90      0.91      0.91       399

    accuracy                           0.91       800
   macro avg       0.91      0.91      0.91       800
weighted avg       0.91      0.91      0.91       800

In [21]:
import torch

X_train, X_test = torch.from_numpy(X_train).float(), torch.from_numpy(X_test).float()

X_train,X_test

(tensor([[ 0.3276, -0.5705, -0.0678,  ...,  0.2335,  0.5660, -0.2717],
         [-0.0610,  0.1417, -0.4052,  ...,  0.1196,  0.3613, -0.7980],
         [-0.3752, -0.4252, -0.1269,  ..., -0.0143,  0.7643, -0.2700],
         ...,
         [ 0.4325, -0.2937, -0.0474,  ..., -0.2400,  0.7884,  0.2124],
         [-0.5705, -0.3987,  0.5463,  ...,  0.1216,  0.1681, -0.2552],
         [-0.4607,  0.3505,  0.0743,  ...,  0.4484, -0.3466, -0.3898]]),
 tensor([[ 0.5633, -0.3074, -0.6687,  ...,  0.0978,  0.3017, -0.0990],
         [ 0.3915, -0.0609, -0.0167,  ...,  0.2408, -0.5960,  0.5310],
         [ 0.3910, -0.1649,  0.5626,  ..., -0.1802, -0.4316,  0.3270],
         ...,
         [-0.1331, -0.6713,  0.3996,  ...,  0.4894,  0.2141, -0.1561],
         [-0.3394, -0.0592,  0.1751,  ..., -0.0158,  0.5250, -0.7572],
         [ 0.0905, -0.3160, -0.0925,  ...,  0.5884,  0.0608, -0.3494]]))

In [22]:
y_train, y_test = torch.from_numpy(y_train).long(), torch.from_numpy(y_test).long()

y_train, y_test

(tensor([1, 1, 0,  ..., 1, 1, 1]),
 tensor([1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
         1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
         0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
         1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
         0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
         0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
         1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
         0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
         0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
         1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
         0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
         1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,

In [23]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

# If we have a gpu, then we'll move our splits into the gpu
# if not, nothing will change

X_train = X_train.to(device)
X_test = X_test.to(device)
y_train = y_train.to(device)
y_test = y_test.to(device)

cpu

In [24]:
class NeuralClassifier(torch.nn.Module):
    def __init__(self, input_size, hidden_size, output_size, dropout_rate):
        super(NeuralClassifier, self).__init__()
        
        # This is the input layer
        
        self.input_layer = torch.nn.Linear(input_size, hidden_size)

        # These are our hidden layers
        
        self.hidden_layer_1 = torch.nn.Linear(hidden_size, 2*hidden_size)
        self.hidden_layer_2 = torch.nn.Linear(2*hidden_size, 4*hidden_size)
        self.hidden_layer_3 = torch.nn.Linear(4*hidden_size, 8*hidden_size)
        self.hidden_layer_4 = torch.nn.Linear(8*hidden_size, 16*hidden_size)
        
        # This is our output layer
        
        self.output_layer = torch.nn.Linear(16*hidden_size, output_size)
        
        # This is our activation function
        
        self.relu = torch.nn.LeakyReLU()
        
        # And this is our dropout
        self.dropout = torch.nn.Dropout(dropout_rate)        
    def forward(self, x):

        x = self.input_layer(x)
        x = self.dropout(x)
        x = self.relu(x)

        # These are our hidden layers

        x = self.hidden_layer_1(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.hidden_layer_2(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.hidden_layer_3(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.hidden_layer_4(x)
        x = self.dropout(x)
        x = self.relu(x)
        
        # This is our output layer
        x = self.output_layer(x)

        return x

In [25]:
input_size = features_no
hidden_size = 100
output_size = len(quality_types)
dropout_rate = 0.38
learning_rate = 0.005
epochs = 400

# Initialize the model

model = NeuralClassifier(input_size, hidden_size, output_size, dropout_rate)

# If a gpu is available, we'll move the model to it
model.to(device)

# Define the loss function and the optimizer

criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [26]:
# Here, we define our training loop

for epoch in range(epochs):
    # Forward pass
    output = model(X_train)
    loss = criterion(output, y_train)
    
    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    # Print loss for this epoch
    
    print(f"Epoch: {epoch+1}. Loss: {loss}")

Epoch: 1. Loss: 0.693683922290802

Epoch: 2. Loss: 0.7786045670509338

Epoch: 3. Loss: 0.8214351534843445

Epoch: 4. Loss: 0.6954700350761414

Epoch: 5. Loss: 0.6935794353485107

Epoch: 6. Loss: 0.6935433745384216

Epoch: 7. Loss: 0.6922466158866882

Epoch: 8. Loss: 0.6888269186019897

Epoch: 9. Loss: 0.6835474967956543

Epoch: 10. Loss: 0.6728588938713074

Epoch: 11. Loss: 0.6494214534759521

Epoch: 12. Loss: 0.6107358336448669

Epoch: 13. Loss: 0.5756077170372009

Epoch: 14. Loss: 0.5666068196296692

Epoch: 15. Loss: 0.557127058506012

Epoch: 16. Loss: 0.5330145955085754

Epoch: 17. Loss: 0.5174807906150818

Epoch: 18. Loss: 0.5292783975601196

Epoch: 19. Loss: 0.48966071009635925

Epoch: 20. Loss: 0.48160067200660706

Epoch: 21. Loss: 0.46972575783729553

Epoch: 22. Loss: 0.4656045436859131

Epoch: 23. Loss: 0.4455145001411438

Epoch: 24. Loss: 0.4306669235229492

Epoch: 25. Loss: 0.4336477220058441

Epoch: 26. Loss: 0.4215097427368164

Epoch: 27. Loss: 0.40561848878860474

Epoch: 28. Loss: 0.4014440178871155

Epoch: 29. Loss: 0.3954727053642273

Epoch: 30. Loss: 0.38106492161750793

Epoch: 31. Loss: 0.3849720358848572

Epoch: 32. Loss: 0.37060150504112244

Epoch: 33. Loss: 0.3690605163574219

Epoch: 34. Loss: 0.3741837441921234

Epoch: 35. Loss: 0.3564335107803345

Epoch: 36. Loss: 0.36247408390045166

Epoch: 37. Loss: 0.35655131936073303

Epoch: 38. Loss: 0.35333961248397827

Epoch: 39. Loss: 0.35535624623298645

Epoch: 40. Loss: 0.33780983090400696

Epoch: 41. Loss: 0.3518405854701996

Epoch: 42. Loss: 0.35105645656585693

Epoch: 43. Loss: 0.3394879996776581

Epoch: 44. Loss: 0.32666394114494324

Epoch: 45. Loss: 0.31945663690567017

Epoch: 46. Loss: 0.32717418670654297

Epoch: 47. Loss: 0.323784738779068

Epoch: 48. Loss: 0.3266647756099701

Epoch: 49. Loss: 0.3271104693412781

Epoch: 50. Loss: 0.31848326325416565

Epoch: 51. Loss: 0.3291091024875641

Epoch: 52. Loss: 0.3166848123073578

Epoch: 53. Loss: 0.3024692237377167

Epoch: 54. Loss: 0.3134842813014984

Epoch: 55. Loss: 0.31623631715774536

Epoch: 56. Loss: 0.30928078293800354

Epoch: 57. Loss: 0.2992149591445923

Epoch: 58. Loss: 0.29385364055633545

Epoch: 59. Loss: 0.30056560039520264

Epoch: 60. Loss: 0.3076915144920349

Epoch: 61. Loss: 0.30259940028190613

Epoch: 62. Loss: 0.2947820723056793

Epoch: 63. Loss: 0.28505098819732666

Epoch: 64. Loss: 0.2942039966583252

Epoch: 65. Loss: 0.29483819007873535

Epoch: 66. Loss: 0.28952839970588684

Epoch: 67. Loss: 0.29053571820259094

Epoch: 68. Loss: 0.29289883375167847

Epoch: 69. Loss: 0.28599557280540466

Epoch: 70. Loss: 0.28498440980911255

Epoch: 71. Loss: 0.2869531810283661

Epoch: 72. Loss: 0.2851160168647766

Epoch: 73. Loss: 0.28329041600227356

Epoch: 74. Loss: 0.2824895679950714

Epoch: 75. Loss: 0.2718192934989929

Epoch: 76. Loss: 0.2770724594593048

Epoch: 77. Loss: 0.275456041097641

Epoch: 78. Loss: 0.2703249752521515

Epoch: 79. Loss: 0.26021260023117065

Epoch: 80. Loss: 0.2743701636791229

Epoch: 81. Loss: 0.27968114614486694

Epoch: 82. Loss: 0.2788257896900177

Epoch: 83. Loss: 0.2689872682094574

Epoch: 84. Loss: 0.2606475055217743

Epoch: 85. Loss: 0.26293647289276123

Epoch: 86. Loss: 0.263599157333374

Epoch: 87. Loss: 0.2718111276626587

Epoch: 88. Loss: 0.2600019574165344

Epoch: 89. Loss: 0.2615199089050293

Epoch: 90. Loss: 0.25738227367401123

Epoch: 91. Loss: 0.24708835780620575

Epoch: 92. Loss: 0.25913798809051514

Epoch: 93. Loss: 0.25585824251174927

Epoch: 94. Loss: 0.24818813800811768

Epoch: 95. Loss: 0.24960878491401672

Epoch: 96. Loss: 0.2542572021484375

Epoch: 97. Loss: 0.25291919708251953

Epoch: 98. Loss: 0.25171032547950745

Epoch: 99. Loss: 0.24938228726387024

Epoch: 100. Loss: 0.25744491815567017

Epoch: 101. Loss: 0.2517646849155426

Epoch: 102. Loss: 0.24299798905849457

Epoch: 103. Loss: 0.24786341190338135

Epoch: 104. Loss: 0.24295957386493683

Epoch: 105. Loss: 0.24109572172164917

Epoch: 106. Loss: 0.25180956721305847

Epoch: 107. Loss: 0.238162562251091

Epoch: 108. Loss: 0.2359040081501007

Epoch: 109. Loss: 0.23351280391216278

Epoch: 110. Loss: 0.22605496644973755

Epoch: 111. Loss: 0.24597230553627014

Epoch: 112. Loss: 0.23613302409648895

Epoch: 113. Loss: 0.236684188246727

Epoch: 114. Loss: 0.2399347424507141

Epoch: 115. Loss: 0.23419445753097534

Epoch: 116. Loss: 0.24269138276576996

Epoch: 117. Loss: 0.2232971042394638

Epoch: 118. Loss: 0.2313009649515152

Epoch: 119. Loss: 0.22828395664691925

Epoch: 120. Loss: 0.24028266966342926

Epoch: 121. Loss: 0.23631125688552856

Epoch: 122. Loss: 0.2205016016960144

Epoch: 123. Loss: 0.22001613676548004

Epoch: 124. Loss: 0.21915334463119507

Epoch: 125. Loss: 0.2311040759086609

Epoch: 126. Loss: 0.22580678761005402

Epoch: 127. Loss: 0.21937179565429688

Epoch: 128. Loss: 0.2169964760541916

Epoch: 129. Loss: 0.22618716955184937

Epoch: 130. Loss: 0.20828476548194885

Epoch: 131. Loss: 0.21954098343849182

Epoch: 132. Loss: 0.22130048274993896

Epoch: 133. Loss: 0.21955546736717224

Epoch: 134. Loss: 0.21513749659061432

Epoch: 135. Loss: 0.22462265193462372

Epoch: 136. Loss: 0.21492022275924683

Epoch: 137. Loss: 0.21453794836997986

Epoch: 138. Loss: 0.21072253584861755

Epoch: 139. Loss: 0.2156972885131836

Epoch: 140. Loss: 0.21066543459892273

Epoch: 141. Loss: 0.21952961385250092

Epoch: 142. Loss: 0.21082288026809692

Epoch: 143. Loss: 0.21350069344043732

Epoch: 144. Loss: 0.20933124423027039

Epoch: 145. Loss: 0.21028363704681396

Epoch: 146. Loss: 0.2154344916343689

Epoch: 147. Loss: 0.20413953065872192

Epoch: 148. Loss: 0.2186908721923828

Epoch: 149. Loss: 0.20682629942893982

Epoch: 150. Loss: 0.21133333444595337

Epoch: 151. Loss: 0.1951003223657608

Epoch: 152. Loss: 0.21655729413032532

Epoch: 153. Loss: 0.2120528370141983

Epoch: 154. Loss: 0.21051160991191864

Epoch: 155. Loss: 0.20561322569847107

Epoch: 156. Loss: 0.2085304707288742

Epoch: 157. Loss: 0.2009318470954895

Epoch: 158. Loss: 0.1971522867679596

Epoch: 159. Loss: 0.20281074941158295

Epoch: 160. Loss: 0.21136128902435303

Epoch: 161. Loss: 0.19790798425674438

Epoch: 162. Loss: 0.1992342323064804

Epoch: 163. Loss: 0.1980917900800705

Epoch: 164. Loss: 0.2063506692647934

Epoch: 165. Loss: 0.1963949203491211

Epoch: 166. Loss: 0.20058119297027588

Epoch: 167. Loss: 0.20037780702114105

Epoch: 168. Loss: 0.20176361501216888

Epoch: 169. Loss: 0.19870424270629883

Epoch: 170. Loss: 0.20254188776016235

Epoch: 171. Loss: 0.19457638263702393

Epoch: 172. Loss: 0.20279815793037415

Epoch: 173. Loss: 0.19932283461093903

Epoch: 174. Loss: 0.18981420993804932

Epoch: 175. Loss: 0.1878395676612854

Epoch: 176. Loss: 0.2026510238647461

Epoch: 177. Loss: 0.19088783860206604

Epoch: 178. Loss: 0.18723323941230774

Epoch: 179. Loss: 0.19108983874320984

Epoch: 180. Loss: 0.1886233389377594

Epoch: 181. Loss: 0.18893228471279144

Epoch: 182. Loss: 0.18509580194950104

Epoch: 183. Loss: 0.19426466524600983

Epoch: 184. Loss: 0.1893760859966278

Epoch: 185. Loss: 0.18555788695812225

Epoch: 186. Loss: 0.18126825988292694

Epoch: 187. Loss: 0.189086452126503

Epoch: 188. Loss: 0.1843796968460083

Epoch: 189. Loss: 0.1925913244485855

Epoch: 190. Loss: 0.18796034157276154

Epoch: 191. Loss: 0.17780236899852753

Epoch: 192. Loss: 0.1960584968328476

Epoch: 193. Loss: 0.17992572486400604

Epoch: 194. Loss: 0.1847352832555771

Epoch: 195. Loss: 0.18517516553401947

Epoch: 196. Loss: 0.18548767268657684

Epoch: 197. Loss: 0.1842089593410492

Epoch: 198. Loss: 0.1855267584323883

Epoch: 199. Loss: 0.17947641015052795

Epoch: 200. Loss: 0.18941183388233185

Epoch: 201. Loss: 0.1843176782131195

Epoch: 202. Loss: 0.18708562850952148

Epoch: 203. Loss: 0.17849750816822052

Epoch: 204. Loss: 0.1930462270975113

Epoch: 205. Loss: 0.19008874893188477

Epoch: 206. Loss: 0.1761256754398346

Epoch: 207. Loss: 0.17358501255512238

Epoch: 208. Loss: 0.1866188943386078

Epoch: 209. Loss: 0.1854017823934555

Epoch: 210. Loss: 0.18106359243392944

Epoch: 211. Loss: 0.17746223509311676

Epoch: 212. Loss: 0.17510387301445007

Epoch: 213. Loss: 0.17757874727249146

Epoch: 214. Loss: 0.1842530220746994

Epoch: 215. Loss: 0.17862823605537415

Epoch: 216. Loss: 0.17757096886634827

Epoch: 217. Loss: 0.18016265332698822

Epoch: 218. Loss: 0.16549384593963623

Epoch: 219. Loss: 0.18594279885292053

Epoch: 220. Loss: 0.17851665616035461

Epoch: 221. Loss: 0.1843297928571701

Epoch: 222. Loss: 0.18077844381332397

Epoch: 223. Loss: 0.1777162402868271

Epoch: 224. Loss: 0.18114612996578217

Epoch: 225. Loss: 0.17986945807933807

Epoch: 226. Loss: 0.17489270865917206

Epoch: 227. Loss: 0.17495691776275635

Epoch: 228. Loss: 0.17335809767246246

Epoch: 229. Loss: 0.1699821650981903

Epoch: 230. Loss: 0.17569765448570251

Epoch: 231. Loss: 0.16356463730335236

Epoch: 232. Loss: 0.17296020686626434

Epoch: 233. Loss: 0.17581874132156372

Epoch: 234. Loss: 0.16762983798980713

Epoch: 235. Loss: 0.1708703637123108

Epoch: 236. Loss: 0.17728133499622345

Epoch: 237. Loss: 0.1781044751405716

Epoch: 238. Loss: 0.1682051718235016

Epoch: 239. Loss: 0.17299245297908783

Epoch: 240. Loss: 0.18308871984481812

Epoch: 241. Loss: 0.16540607810020447

Epoch: 242. Loss: 0.1630830317735672

Epoch: 243. Loss: 0.17260430753231049

Epoch: 244. Loss: 0.17271730303764343

Epoch: 245. Loss: 0.1770215928554535

Epoch: 246. Loss: 0.1714259684085846

Epoch: 247. Loss: 0.16474542021751404

Epoch: 248. Loss: 0.17040404677391052

Epoch: 249. Loss: 0.1641954779624939

Epoch: 250. Loss: 0.16862131655216217

Epoch: 251. Loss: 0.17836952209472656

Epoch: 252. Loss: 0.16412270069122314

Epoch: 253. Loss: 0.17828553915023804

Epoch: 254. Loss: 0.17947599291801453

Epoch: 255. Loss: 0.16150175034999847

Epoch: 256. Loss: 0.16426831483840942

Epoch: 257. Loss: 0.16898809373378754

Epoch: 258. Loss: 0.16209307312965393

Epoch: 259. Loss: 0.16871529817581177

Epoch: 260. Loss: 0.15732716023921967

Epoch: 261. Loss: 0.1594363898038864

Epoch: 262. Loss: 0.1665208488702774

Epoch: 263. Loss: 0.1719222515821457

Epoch: 264. Loss: 0.17246775329113007

Epoch: 265. Loss: 0.16812381148338318

Epoch: 266. Loss: 0.1597663164138794

Epoch: 267. Loss: 0.163302481174469

Epoch: 268. Loss: 0.16819483041763306

Epoch: 269. Loss: 0.16604013741016388

Epoch: 270. Loss: 0.16383366286754608

Epoch: 271. Loss: 0.1647772341966629

Epoch: 272. Loss: 0.1691785603761673

Epoch: 273. Loss: 0.16814422607421875

Epoch: 274. Loss: 0.17022563517093658

Epoch: 275. Loss: 0.15487363934516907

Epoch: 276. Loss: 0.165577694773674

Epoch: 277. Loss: 0.15755338966846466

Epoch: 278. Loss: 0.16302700340747833

Epoch: 279. Loss: 0.16648857295513153

Epoch: 280. Loss: 0.15163110196590424

Epoch: 281. Loss: 0.15977072715759277

Epoch: 282. Loss: 0.1611822247505188

Epoch: 283. Loss: 0.16258129477500916

Epoch: 284. Loss: 0.16193737089633942

Epoch: 285. Loss: 0.16291673481464386

Epoch: 286. Loss: 0.16188833117485046

Epoch: 287. Loss: 0.16368645429611206

Epoch: 288. Loss: 0.15655963122844696

Epoch: 289. Loss: 0.15913477540016174

Epoch: 290. Loss: 0.1555566042661667

Epoch: 291. Loss: 0.16872049868106842

Epoch: 292. Loss: 0.16200609505176544

Epoch: 293. Loss: 0.15771381556987762

Epoch: 294. Loss: 0.1536194533109665

Epoch: 295. Loss: 0.16198353469371796

Epoch: 296. Loss: 0.155201256275177

Epoch: 297. Loss: 0.15356619656085968

Epoch: 298. Loss: 0.15626417100429535

Epoch: 299. Loss: 0.1553850769996643

Epoch: 300. Loss: 0.15516053140163422

Epoch: 301. Loss: 0.16200347244739532

Epoch: 302. Loss: 0.15591906011104584

Epoch: 303. Loss: 0.14945489168167114

Epoch: 304. Loss: 0.1566447615623474

Epoch: 305. Loss: 0.15354284644126892

Epoch: 306. Loss: 0.15169349312782288

Epoch: 307. Loss: 0.15620329976081848

Epoch: 308. Loss: 0.1539427638053894

Epoch: 309. Loss: 0.1510275900363922

Epoch: 310. Loss: 0.15519988536834717

Epoch: 311. Loss: 0.15534347295761108

Epoch: 312. Loss: 0.14285768568515778

Epoch: 313. Loss: 0.1590472161769867

Epoch: 314. Loss: 0.14590877294540405

Epoch: 315. Loss: 0.14710327982902527

Epoch: 316. Loss: 0.15545660257339478

Epoch: 317. Loss: 0.15460465848445892

Epoch: 318. Loss: 0.15188361704349518

Epoch: 319. Loss: 0.15550215542316437

Epoch: 320. Loss: 0.14512251317501068

Epoch: 321. Loss: 0.15036332607269287

Epoch: 322. Loss: 0.15966930985450745

Epoch: 323. Loss: 0.1474338173866272

Epoch: 324. Loss: 0.14698247611522675

Epoch: 325. Loss: 0.1568261682987213

Epoch: 326. Loss: 0.15541215240955353

Epoch: 327. Loss: 0.14699171483516693

Epoch: 328. Loss: 0.1604420691728592

Epoch: 329. Loss: 0.1455911248922348

Epoch: 330. Loss: 0.15060211718082428

Epoch: 331. Loss: 0.14199687540531158

Epoch: 332. Loss: 0.15045467019081116

Epoch: 333. Loss: 0.14246274530887604

Epoch: 334. Loss: 0.1452869474887848

Epoch: 335. Loss: 0.14864392578601837

Epoch: 336. Loss: 0.14737874269485474

Epoch: 337. Loss: 0.15389961004257202

Epoch: 338. Loss: 0.13810686767101288

Epoch: 339. Loss: 0.13834768533706665

Epoch: 340. Loss: 0.1546628326177597

Epoch: 341. Loss: 0.15810143947601318

Epoch: 342. Loss: 0.1443919986486435

Epoch: 343. Loss: 0.14623017609119415

Epoch: 344. Loss: 0.1417039930820465

Epoch: 345. Loss: 0.15332090854644775

Epoch: 346. Loss: 0.15692812204360962

Epoch: 347. Loss: 0.1477745771408081

Epoch: 348. Loss: 0.14165784418582916

Epoch: 349. Loss: 0.15248872339725494

Epoch: 350. Loss: 0.14350435137748718

Epoch: 351. Loss: 0.14824266731739044

Epoch: 352. Loss: 0.14908228814601898

Epoch: 353. Loss: 0.1387491673231125

Epoch: 354. Loss: 0.1454063355922699

Epoch: 355. Loss: 0.1538165658712387

Epoch: 356. Loss: 0.15753310918807983

Epoch: 357. Loss: 0.14730268716812134

Epoch: 358. Loss: 0.1568957269191742

Epoch: 359. Loss: 0.1462438404560089

Epoch: 360. Loss: 0.150603786110878

Epoch: 361. Loss: 0.14492298662662506

Epoch: 362. Loss: 0.15632514655590057

Epoch: 363. Loss: 0.14384005963802338

Epoch: 364. Loss: 0.13893772661685944

Epoch: 365. Loss: 0.1446847766637802

Epoch: 366. Loss: 0.14512278139591217

Epoch: 367. Loss: 0.14061155915260315

Epoch: 368. Loss: 0.13894157111644745

Epoch: 369. Loss: 0.141774982213974

Epoch: 370. Loss: 0.1380998194217682

Epoch: 371. Loss: 0.1330580711364746

Epoch: 372. Loss: 0.14862938225269318

Epoch: 373. Loss: 0.13599659502506256

Epoch: 374. Loss: 0.13325846195220947

Epoch: 375. Loss: 0.13827602565288544

Epoch: 376. Loss: 0.1411719173192978

Epoch: 377. Loss: 0.1423862725496292

Epoch: 378. Loss: 0.13726752996444702

Epoch: 379. Loss: 0.13879981637001038

Epoch: 380. Loss: 0.14339697360992432

Epoch: 381. Loss: 0.14162249863147736

Epoch: 382. Loss: 0.13545268774032593

Epoch: 383. Loss: 0.12929216027259827

Epoch: 384. Loss: 0.14315690100193024

Epoch: 385. Loss: 0.14688558876514435

Epoch: 386. Loss: 0.1443551480770111

Epoch: 387. Loss: 0.14680173993110657

Epoch: 388. Loss: 0.14284773170948029

Epoch: 389. Loss: 0.13335564732551575

Epoch: 390. Loss: 0.15703184902668

Epoch: 391. Loss: 0.1329331248998642

Epoch: 392. Loss: 0.13523100316524506

Epoch: 393. Loss: 0.14293526113033295

Epoch: 394. Loss: 0.14219437539577484

Epoch: 395. Loss: 0.1380537897348404

Epoch: 396. Loss: 0.14260001480579376

Epoch: 397. Loss: 0.139193594455719

Epoch: 398. Loss: 0.14037996530532837

Epoch: 399. Loss: 0.1398945450782776

Epoch: 400. Loss: 0.13628245890140533

In [27]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

# Just out of curiosity let's check the amount of trainable parameters of our NN
count_parameters(model)

1707002

In [28]:
model.eval()
output = model(X_test)
y_pred_nn = torch.argmax(output, dim=1)

y_pred_nn


tensor([1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
        0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
        1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
        1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
        1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,

In [29]:
print(classification_report(y_test.cpu(), y_pred_nn.cpu(), target_names=quality_types))


precision    recall  f1-score   support

        good       0.93      0.95      0.94       401
         bad       0.94      0.93      0.94       399

    accuracy                           0.94       800
   macro avg       0.94      0.94      0.94       800
weighted avg       0.94      0.94      0.94       800